name: Daily Commit

on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Append date to daily-log.txt
        run: |
          echo "Daily log: $(date -u +"%Y-%m-%d %H:%M UTC")" >> daily-log.txt

      - name: Commit and push
        run: |
          git config user.name "AutoCommitBot"
          git config user.email "autocommit@users.noreply.github.com"
          git add daily-log.txt
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Add daily log entry: $(date -u +'%Y-%m-%d %H:%M UTC')"
            git push
          fi
